spring:
  application:
    name: splitmart

  datasource:
    url: jdbc:postgresql://localhost:5432/splitmart
    username: splitmart
    password: splitmart
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
