spring:
  application:
    name: splitmart

  datasource:
    url: jdbc:postgresql://localhost:5432/splitmart
    username: splitmart
    password: splitmart
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
